# Generated by Django 3.2.14 on 2022-08-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmacia_enderecos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('delecao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=50)),
                ('dtaNascimento', models.DateField()),
                ('CPF', models.CharField(max_length=14)),
                ('RG', models.CharField(blank=True, default='', max_length=14)),
                ('CEL', models.CharField(blank=True, default='', max_length=14)),
                ('SEXO', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmacia_enderecos.endereco')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['nome'],
                'unique_together': {('nome', 'CPF', 'RG', 'CEL', 'email')},
            },
        ),
    ]
