# Generated by Django 3.2.14 on 2022-07-30 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('delecao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('CNPJ', models.CharField(blank=True, default='', max_length=14)),
                ('telefone1', models.CharField(max_length=15)),
                ('telefone2', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('site_url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricante',
                'unique_together': {('nome', 'CNPJ')},
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('delecao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('CNPJ', models.CharField(blank=True, default='', max_length=14)),
                ('telefone1', models.CharField(max_length=15)),
                ('telefone2', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('site_url', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'unique_together': {('nome', 'CNPJ')},
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('delecao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('medida', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
            },
        ),
        migrations.CreateModel(
            name='TipoDeUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('delecao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Tipo de Uso',
                'verbose_name_plural': 'Tipos de Uso',
            },
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('delecao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Tipo Produto',
                'verbose_name_plural': 'Tipo Produtos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('delecao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao_produto', models.TextField(blank=True, default='', max_length=500)),
                ('lote', models.CharField(max_length=55)),
                ('quantidade', models.IntegerField()),
                ('validade', models.DateTimeField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('peso_liquido', models.CharField(blank=True, default='', max_length=55)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabricantes', to='produtos.fabricante')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='produtos.fornecedor')),
                ('medida', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='produtos.medida')),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_produtos', to='produtos.tipoproduto')),
                ('tipo_uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_de_uso', to='produtos.tipodeuso')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'unique_together': {('nome', 'fabricante', 'lote')},
            },
        ),
    ]
