# Generated by Django 3.2.14 on 2022-07-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('delecao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('endereco', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('UF', models.CharField(max_length=50)),
                ('CEP', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['endereco'],
                'unique_together': {('endereco', 'CEP', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('delecao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=50)),
                ('dtaNascimento', models.DateField()),
                ('CPF', models.CharField(max_length=14)),
                ('RG', models.CharField(blank=True, default='', max_length=14)),
                ('CEL', models.CharField(blank=True, default='', max_length=14)),
                ('SEXO', models.CharField(blank=True, default='', max_length=10)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('enderecos', models.ManyToManyField(to='clientes.Endereco')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
                'unique_together': {('nome', 'CPF', 'RG')},
            },
        ),
    ]
